export const CountryList = [
    'Brasil',
    'Argentina',
    'Uruguai',
    'Equador',
    'Chile',
    'Portugal',
    'Espanha',
    'Dinamarca',
    'Noruega',
    'Alemanha',
    'Croacia',
    'Bosnia e Herzegovina',
    'Paraguai',
    'Colombia',
    'China',
    'Irao',
    'Franca',
    'Japao',
    'Costa Rica',
    'Georgia',
    'Russia',
    'Estados Unidos',
    'Inglaterra',
    'Canada',
    'Servia',
    'Nigeria',
    'Holanda',
    'Grecia',
    'Ghana',
    'Irlanda',
    'Angola',
    'Italia',
    'Venezuela',
    'Libia',
    'Bolivia',
    'Bulgaria',
    'Peru',
    'Guatemala',
    'Australia',
    'Moldavia',
    'Coreia do Sul',
    'Turquia',
    'Chequia',
    'Suecia'
]